[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Linaro Solutions Hub"
authors = [{name = "Philip Colmer", email = "philip.colmer@linaro.org"}]
dynamic = ["version", "description"]
